package cz.judas.jan.advent.year2025

import cz.judas.jan.advent.InputData
import org.junit.jupiter.api.Test
import org.scalatest.Assertions.assert

class Day07Test:
  private val input = InputData.fromString(
    """
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
    """
  )

  @Test
  def part1Works(): Unit =
    assert(Day07.part1(input) == 21)

  @Test
  def part2Works(): Unit =
    assert(Day07.part2(input) == 40)
