package cz.judas.jan.advent.year2024

import cz.judas.jan.advent.InputData
import org.junit.jupiter.api.Test
import org.scalatest.Assertions.assert

class Day08Test:
  private val input = InputData.fromString(
    """
      ............
      ........0...
      .....0......
      .......0....
      ....0.......
      ......A.....
      ............
      ............
      ........A...
      .........A..
      ............
      ............
    """
  )

  @Test
  def part1Works(): Unit =
    assert(Day08.part1(input) == 14)

  @Test
  def part2Works(): Unit =
    assert(Day08.part2(input) == 34)
